from .check_reports import CheckReports
from .check_reports_menu_ajax import CheckReportsMenuAjax
from .choose_course_to_check import ChooseCourseToCheck
from .course_stats import CourseStats
from .courses_of_tutor_ajax import CoursesOfTutorXHR
from .download_report import DownloadReport
from .search_reports import ReportsSearcher
from .add_course import AddCourse
from .reports_archive import ReportsArchive
from .tutor_main import tutor
