from .ajax import CheckReportsMenuAjax
from .ajax import CoursesOfTutorXHR
from .add_course import AddCourse
from .check_reports import CheckReports
from .choose_course_to_check import ChooseCourseToCheck
from .course_stats import CourseStats
from .download_report import DownloadReport
from .make_announcement import MakeAnnouncement
from .reports_archive import ReportsArchive
from .search_reports import ReportsSearcher
from .tutor_main import tutor
